# {0}
trigger:
  branches:
    include:
    - '*'

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

parameters:
- name: images
  type: object
  default: [{1} ]

jobs:
- ${{ each image in parameters.images }}:
  - job:
    displayName: '${{ image }}'
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: DockerHub
    - script: 'docker pull ${{ image }}'
      displayName: 'docker pull ${{ image }}'
    - task: Docker@2
      displayName: Logout of Docker Hub
      inputs:
        command: logout
        containerRegistry: DockerHub
